Feat/ev 993/onion architecture
LuanFortunatoW/EverestBackendDotnet pull request #2
Opened 2022-11-17 15:38 UTC by LuanFortunatoW

# Card
[EV-993](https://warren.atlassian.net/browse/EV-993)

# Feats

Validações devem pertencer a camada de aplicação;

Única responsabilidade da api é receber requisições, endereçar requisições a camada de aplicação e retornar status code/response de acordo com o retorno da camada de aplicação.

2022-11-17 16:28 UTC, gregoryzimmerwarren reviewed
Deixei alguns comentários. Em relação a criação de outras interfaces espera por mais reviews para ter certeza.

2022-11-17 16:28 UTC, gregoryzimmerwarren commented on API/API.csproj
> +    <ProjectReference Include="..\DomainServices\DomainServices.csproj" />
A tua API não tem dependência da tua DomainServices, somente da AppServices.
Como a App vai ter a dependência da Domain, a API também acaba tendo por consequência.

2022-11-17 16:28 UTC, gregoryzimmerwarren commented on API/Controllers/BaseController.cs
> +                return BadRequest(message);
Podes mudar de BadRequest para um NoContent. Pensando que na verdade não foi um erro do usuário ao fazer a requisição, mas sim que não há conteúdo para ser retornado.

2022-11-17 16:28 UTC, gregoryzimmerwarren commented on API/Controllers/BaseController.cs
> +            }
Acho que não precisa. Acredito que o único erro seria colocar um ID que não conste no banco.

2022-11-17 16:28 UTC, gregoryzimmerwarren commented on API/Program.cs
> +builder.Services.AddControllers();
```suggestion
builder.Services.AddControllers();
```

2022-11-17 16:28 UTC, gregoryzimmerwarren commented on API/Controllers/BaseController.cs
> +    public class BaseController<S, T> : ControllerBase where S : BaseService<T> where T : BaseModel
```suggestion
    public class BaseController<S, T> : ControllerBase where S : IService<T> where T : BaseModel
```

2022-11-17 16:28 UTC, gregoryzimmerwarren commented on API/Controllers/CustomerController.cs
> +    public class CustomerController : BaseController<CustomerService, Customer>
```suggestion
    public class CustomerController : BaseController<ICustomerService, Customer>
```

2022-11-17 16:28 UTC, gregoryzimmerwarren commented on API/Controllers/CustomerController.cs
> +    public class CustomerController : BaseController<CustomerService, Customer>
Tens que criar uma interface para cara um dos teus services, mesmo com o genérico. Nesse caso vai ser apenas um ICustomerService que implementa o teu IService.

2022-11-17 16:28 UTC, gregoryzimmerwarren commented on API/Program.cs
> +builder.Services.AddSingleton<CustomerService, CustomerService>();
```suggestion
builder.Services.AddSingleton<ICustomerService, CustomerService>();
```

2022-11-17 16:28 UTC, gregoryzimmerwarren commented on API/Program.cs
> +builder.Services.AddSingleton<CustomerService, CustomerService>();
Além disso tem que colocar todas as demais injeções de dependência necessárias.

2022-11-17 16:28 UTC, gregoryzimmerwarren commented on AppServices/AppServices.csproj
> +    <ProjectReference Include="..\DomainModels\DomainModels.csproj" />
Aqui tem que ter referência ao DomainService. Como o Service tem referência ao Model, esse último vem por consequência para cá.

2022-11-17 16:28 UTC, gregoryzimmerwarren commented on Data/Services/CustomerService.cs
> +
```suggestion
```

2022-11-17 16:31 UTC, santosclaudinei-warren commented on API/Controllers/BaseController.cs
> +                return Ok("Customer updated");
```suggestion
                return Ok();
```

2022-11-17 16:32 UTC, santosclaudinei-warren commented on DomainServices/Services/BaseService.cs
> +                throw new ArgumentNullException($"Id {id} not found");
```suggestion
                throw new ArgumentNullException($"Customer for Id: {id} not found");
```

2022-11-17 16:32 UTC, DevClaudinei commented on DomainServices/Services/BaseService.cs
> +                throw new ArgumentNullException($"Id {model.Id} not found");
```suggestion
                throw new ArgumentNullException($"Customer for Id: {id} not found");
```

2022-11-17 16:43 UTC, santosclaudinei-warren commented on DomainServices/Services/CustomerService.cs
> +            bool emailAlreadyExists = _customers.Any(customer => customer.Email == updatedCustomer.Email && customer.Id != updatedCustomer.Id);
```suggestion
            var emailAlreadyExists = _customers.Any(customer => customer.Email == updatedCustomer.Email && customer.Id != updatedCustomer.Id);
```

2022-11-17 16:44 UTC, santosclaudinei-warren commented on DomainServices/Services/CustomerService.cs
> +            bool cpfAlreadyExists = _customers.Any(customer => customer.Cpf == updatedCustomer.Cpf && customer.Id != updatedCustomer.Id);
```suggestion
            var cpfAlreadyExists = _customers.Any(customer => customer.Cpf == updatedCustomer.Cpf && customer.Id != updatedCustomer.Id);
```

2022-11-17 16:44 UTC, DevClaudinei commented on DomainServices/Services/CustomerService.cs
> +            bool emailAlreadyExists = _customers.Any(customer => customer.Email == createdCustomer.Email);
```suggestion
            var emailAlreadyExists = _customers.Any(customer => customer.Email == createdCustomer.Email);
```

2022-11-17 16:44 UTC, DevClaudinei commented on DomainServices/Services/CustomerService.cs
> +            bool cpfAlreadyExists = _customers.Any(customer => customer.Cpf == createdCustomer.Cpf);
```suggestion
            var cpfAlreadyExists = _customers.Any(customer => customer.Cpf == createdCustomer.Cpf);
```

2022-11-17 16:54 UTC, santosclaudinei-warren commented on DomainServices/Interfaces/IService.cs
> +    internal interface IService<T> where T : BaseModel
```suggestion
    internal interface ICustomerService<T> where T : BaseModel
```

2022-11-17 16:55 UTC, santosclaudinei-warren commented on DomainModels/StringExtensions.cs
>          internal static string formatCellphone(this string cpf)
```suggestion
        public static string formatCellphone(this string cpf)
```

2022-11-17 16:56 UTC, santosclaudinei-warren commented on DomainModels/StringExtensions.cs
>          internal static string formatPostalCode(this string cpf)
```suggestion
        public static string formatPostalCode(this string cpf)
```

2022-11-17 18:26 UTC, gregoryzimmerwarren reviewed
Deixei novos comentários

2022-11-17 18:26 UTC, gregoryzimmerwarren commented on API/Controllers/BaseController.cs
> +                return NotFound();
Acredito que seja melhor mudar para NoContent()

2022-11-17 18:26 UTC, gregoryzimmerwarren commented on DomainModels/StringExtensions.cs
> +            return cpf.Trim().Replace("+", "").Replace("-", "").Replace("(", "").Replace(")", "");
Não é this string cpf nesses também

2022-11-17 18:26 UTC, gregoryzimmerwarren commented on DomainServices/Services/BaseService.cs
> +                ?? throw new ArgumentNullException($"Id {id} not found");
```suggestion
                ?? throw new ArgumentNullException($"Id: {id} not found");
```

2022-11-17 18:26 UTC, gregoryzimmerwarren commented on DomainServices/Services/BaseService.cs
> +                throw new ArgumentNullException($"Id {model.Id} not found");
```suggestion
                throw new ArgumentNullException($"Id: {model.Id} not found");
```

2022-11-17 18:40 UTC, gregoryzimmerwarren approved these changes

2022-11-17 19:52 UTC, santosclaudinei-warren commented on DomainServices/Services/BaseService.cs
> +using System.Reflection;
não está sendo utilizado.

2022-11-17 19:52 UTC, santosclaudinei-warren commented on DomainServices/Services/BaseService.cs
> +                throw new ArgumentNullException($"Id: {model.Id} not found");
```suggestion
                throw new ArgumentNullException($"Customer for Id: {model.Id} not found");
```

2022-11-17 19:53 UTC, santosclaudinei-warren commented on DomainServices/Services/BaseService.cs
> +                ?? throw new ArgumentNullException($"Id: {id} not found");
```suggestion
                ?? throw new ArgumentNullException($"Customer for Id: {id} not found");
```

2022-11-17 20:06 UTC, santosclaudinei-warren commented on API/Controllers/BaseController.cs
> +        private readonly S _service;
Acredito que falta referenciar uma interface na camada de aplicação (AppServices) para que ela chame a camada de domínio.
Camada de api se comunica apenas com camada de aplicação(AppServices), camada de aplicação(AppServices) se comunica com camada de domínio(DomainServices) e outras AppServices.

2022-11-18 16:59 UTC, LucasPerinWarren commented on API/Controllers/BaseController.cs
> +        }
Temos apenas uma appService e consequentemente apenas uma controller, não há necessidade de criar complexidade a mais, com classes genéricas

2022-11-18 17:00 UTC, LucasPerinWarren commented on AppServices/Interfaces/IAppService.cs
> +    {
Mesmo caso acima, pode fazer direto a interface da entidade, aqui teremos complexidade desnecessária.

2022-11-18 17:02 UTC, LucasPerinWarren commented on AppServices/Services/BaseAppService.cs
> +    {
[Comentário Acima](https://github.com/LuanFortunatoW/EverestBackendDotnet/pull/2/files#r1026667725)

2022-11-18 17:05 UTC, LucasPerinWarren commented on DomainServices/DomainServices.csproj
> +</Project>
Isso está duplicado no PR, verificar se é conflito no commit ou realmente existem os 2 arquivos no projeto.
```suggestion
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DomainModels\DomainModels.csproj" />
  </ItemGroup>

</Project>
```

2022-11-18 17:06 UTC, LucasPerinWarren commented on DomainServices/Interfaces/IService.cs
> +        void Create(T model);
[Comentário Acima](https://github.com/LuanFortunatoW/EverestBackendDotnet/pull/2/files#r1026669457)

2022-11-18 17:06 UTC, LucasPerinWarren commented on DomainServices/Services/BaseService.cs
> +    {
[Comentário Acima](https://github.com/LuanFortunatoW/EverestBackendDotnet/pull/2/files#r1026669457)

2022-11-18 17:06 UTC, LucasPerinWarren requested changes
Verificar Comentários.

2022-11-21 11:30 UTC, LucasPerinWarren commented on API/Controllers/CustomerController.cs
>          {
Utilizaremos essa controller somente aqui, e ela não será sobrescrita, por isso, o uso do virtual não se faz necessário.
```suggestion
        public IActionResult Get()
        {
```

2022-11-21 11:30 UTC, LucasPerinWarren commented on API/Controllers/CustomerController.cs
>          {
[Comentário Acima](https://github.com/LuanFortunatoW/EverestBackendDotnet/pull/2/files#r1027898541)
```suggestion
        public IActionResult GetById(long id)
        {
```

2022-11-21 11:31 UTC, LucasPerinWarren commented on API/Controllers/CustomerController.cs
>          {
[Comentário Acima](https://github.com/LuanFortunatoW/EverestBackendDotnet/pull/2/files#r1027898541)
```suggestion
        public IActionResult Create(Customer customer)
        {
```

2022-11-21 11:31 UTC, LucasPerinWarren commented on API/Controllers/CustomerController.cs
>          {
[Comentário Acima](https://github.com/LuanFortunatoW/EverestBackendDotnet/pull/2/files#r1027898541)
```suggestion
        public IActionResult Delete(long id)
        {
```

2022-11-21 11:32 UTC, LucasPerinWarren commented on AppServices/Services/CustomerAppService.cs
> +        {
Mesmo caso da controller, somente usaríamos o virtual se essa classe fosse herdada em outra, como não é o caso, o uso é dispensável.
```suggestion
        public void Create(Customer customer)
        {
```

2022-11-21 11:32 UTC, LucasPerinWarren commented on AppServices/Services/CustomerAppService.cs
> +        {
[Comentário Acima](https://github.com/LuanFortunatoW/EverestBackendDotnet/pull/2/files#r1027900637)
```suggestion
        public void Delete(long id)
        {
```

2022-11-21 11:33 UTC, LucasPerinWarren commented on AppServices/Services/CustomerAppService.cs
> +        {
[Comentário Acima](https://github.com/LuanFortunatoW/EverestBackendDotnet/pull/2/files#r1027900637)
```suggestion
        public IEnumerable<Customer> GetAll()
        {
```

2022-11-21 11:33 UTC, LucasPerinWarren commented on AppServices/Services/CustomerAppService.cs
> +        {
[Comentário Acima](https://github.com/LuanFortunatoW/EverestBackendDotnet/pull/2/files#r1027900637)
```suggestion
        public Customer GetById(long id)
        {
```

2022-11-21 11:33 UTC, LucasPerinWarren commented on AppServices/Services/CustomerAppService.cs
> +        {
[Comentário Acima](https://github.com/LuanFortunatoW/EverestBackendDotnet/pull/2/files#r1027900637)
```suggestion
        public void Update(Customer customer)
        {
```

2022-11-21 11:34 UTC, LucasPerinWarren commented on DomainModels/IModel.cs
> +    }
Utilizar long para Id ao invés de int.
```suggestion
        long Id { get; set; }
    }
```

2022-11-21 11:36 UTC, LucasPerinWarren commented on DomainServices/Services/CustomerService.cs
> +        {
[Comentário Acima](https://github.com/LuanFortunatoW/EverestBackendDotnet/pull/2/files#r1027900637)
```suggestion
        public void Create(Customer customer)
        {
```

2022-11-21 11:36 UTC, LucasPerinWarren commented on DomainServices/Services/CustomerService.cs
> +        {
[Comentário Acima](https://github.com/LuanFortunatoW/EverestBackendDotnet/pull/2/files#r1027900637)
```suggestion
        public void Delete(long id)
        {
```

2022-11-21 11:36 UTC, LucasPerinWarren commented on DomainServices/Services/CustomerService.cs
> +        {
[Comentário Acima](https://github.com/LuanFortunatoW/EverestBackendDotnet/pull/2/files#r1027900637)
```suggestion
        public IEnumerable<Customer> GetAll()
        {
```

2022-11-21 11:36 UTC, LucasPerinWarren commented on DomainServices/Services/CustomerService.cs
> +        {
[Comentário Acima](https://github.com/LuanFortunatoW/EverestBackendDotnet/pull/2/files#r1027900637)
```suggestion
        public Customer GetById(long id)
        {
```

2022-11-21 11:36 UTC, LucasPerinWarren commented on DomainServices/Services/CustomerService.cs
> +        {
[Comentário Acima](https://github.com/LuanFortunatoW/EverestBackendDotnet/pull/2/files#r1027900637)
```suggestion
        public void Update(Customer customer)
        {
```

2022-11-21 11:42 UTC, LucasPerinWarren requested changes
Verificar comentários.

2022-11-21 11:46 UTC, LucasPerinWarren commented on API/Controllers/CustomerController.cs
>          [HttpDelete]
O Delete está sendo feito através de um Id, portanto é recomendado que o mesmo seja passado como parâmetro, similar ao GetById.
```suggestion

        [HttpDelete("{id}")]
```

2022-11-21 11:47 UTC, LucasPerinWarren requested changes
Mais um

2022-11-21 12:14 UTC, LucasPerinWarren approved these changes

2022-11-21 15:00 UTC, viniciusoliveira-warren commented on AppServices/AppServices.csproj
> +  </ItemGroup>
Pacote duplicado na api, pode remover na api e manter apenas esse

2022-11-21 16:57 UTC, AlanMDomingues commented on DomainServices/Services/CustomerService.cs
> +                throw new ArgumentException("Cpf already exists");
Ambas validações podem serem feitas diretamente no `if`, sem precisar armazenar em uma variável, pois estão sendo utilizadas apenas nos `if`s

2022-11-21 17:40 UTC, viniciusoliveira-warren approved these changes

2022-11-21 17:46 UTC, viniciusoliveira-warren requested changes

2022-11-21 17:46 UTC, viniciusoliveira-warren commented on DomainModels/Customer.cs
> +        long IModel.Id { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
Id duplicado

2022-11-21 17:52 UTC, AlanmWarren approved these changes

2022-11-21 17:59 UTC, merged