Feat/ev 994/boas praticas
LuanFortunatoW/EverestBackendDotnet pull request #3
Opened 2022-11-21 18:10 UTC by LuanFortunatoW

# Card
[EV-994](https://warren.atlassian.net/browse/EV-994)

# Feats

- Requests recebidas pelos endpoints da api devem ser mapeadas para entidades de domínio;

- Antes das AppServices retornarem os dados para api devemos mapear a(s) entidade(s) de domínio para entidade(s) de response da api;

- Todos os mapeamentos de entidade(s) devem serem feitas na camada de aplicação(Application)

2022-11-21 19:22 UTC, gregoryzimmerwarren requested changes
Deixei alguns comentários e sugestões.

Qualquer dúvida estou a disposição.

2022-11-21 19:22 UTC, gregoryzimmerwarren commented on API/Program.cs
> +using System.Reflection;
Te recomendo utilizar, não apenas aqui, mas em todos os teus arquivos o Ctrl + R + G, esse atalho vai remover usings não utilizados e também vai colocar os utilizados em ordem alfabética.

2022-11-21 19:22 UTC, gregoryzimmerwarren commented on AppModels/Customers/CustomerResult.cs
> +    }
Acredito que vale pensar quais as informações que são interessantes de trazer par ao usuário. Não estou dizendo que o que tu fez está errado, mas será que todas essas informações são relevantes para se apresentar? Fica a reflexão. No mais, precisa colocar o Id no construtor.

2022-11-21 19:22 UTC, gregoryzimmerwarren commented on AppServices/AppServices.csproj
> +		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
```suggestion
		<PackageReference Include="AutoMapper" Version="11.0.1" />
```

2022-11-21 19:22 UTC, gregoryzimmerwarren commented on AppServices/AppServices.csproj
> +		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
Talvez tenhas que fazer algumas mudanças baseado no package

2022-11-21 19:22 UTC, gregoryzimmerwarren commented on API/Controllers/CustomerController.cs
> +                return Created("Customer: ", customer);
```suggestion
                return Created("Id: ", id);
```

2022-11-21 19:22 UTC, gregoryzimmerwarren commented on API/Controllers/CustomerController.cs
> +                return Created("Customer: ", customer);
Muda tua tinha 53 para:

var id = _appService.Create(customer);

2022-11-21 19:22 UTC, gregoryzimmerwarren commented on API/Controllers/CustomerController.cs
> +                return Created("Customer: ", customer);
É mais interessante tu mudar teu método para que ele retorne apenas o Id que é um long do que ficar trazendo toda a entidade como resposta.

2022-11-21 19:22 UTC, gregoryzimmerwarren commented on AppServices/Interfaces/ICustomerAppService.cs
> +        void Create(CustomerCreate customer);
```suggestion
        long Create(CustomerCreate customer);
```

2022-11-21 19:22 UTC, gregoryzimmerwarren commented on AppServices/Services/CustomerAppService.cs
> +        public CustomerAppService(ICustomerService service, IMapper mapper)
```suggestion
        private readonly IMapper _mapper;
        
        public CustomerAppService(ICustomerService service, IMapper mapper)
```

2022-11-21 19:22 UTC, gregoryzimmerwarren commented on AppServices/Services/CustomerAppService.cs
> +        public void Create(CustomerCreate customer)
```suggestion
        public long Create(CustomerCreate customer)
```

2022-11-21 19:22 UTC, gregoryzimmerwarren commented on AppServices/Services/CustomerAppService.cs
> +            _service.Create(_mappedCustomer);
```suggestion
            return _service.Create(_mappedCustomer);
```

2022-11-21 19:22 UTC, gregoryzimmerwarren commented on DomainModels/Customer.cs
>  {
Não estou conseguindo fazer alterações nas outras linhas, então, nas linhas 27, 28 e 34: você já faz a formatação destes parâmetros no CustomerCreate e no CustomerUpdate, então quando tu mapeia para mandar para cá, elas já estão formatadas.

2022-11-21 19:22 UTC, gregoryzimmerwarren commented on DomainModels/Customer.cs
>          public string EmailConfirmation { get; set; }
Não é necessário armazenar o emailConfirmation, ele é útil para a validação do email, que deve ser feita pro  CustomerCreate e para o CustomerUpdate (você precisa fazer), então não a mais a necessidade de se manter ele aqui.

2022-11-21 19:22 UTC, gregoryzimmerwarren commented on DomainModels/DomainModels.csproj
> +
```suggestion
```

2022-11-21 19:22 UTC, gregoryzimmerwarren commented on DomainModels/DomainModels.csproj
> +
Com a alteração anterior essa dependência não será mais necessária.

2022-11-21 19:22 UTC, gregoryzimmerwarren commented on Infrastructure.CrossCuting/Extensions/StringExtensions.cs
>              return cellphone.Trim().Replace("+", "").Replace("-", "").Replace("(", "").Replace(")", "");
Te recomendo:

return Cpf.Trim().Replace(".", "").Replace("-", "").Replace(",", "").Replace(" ", "");

return Postalcode.Trim().Replace(".", "").Replace("-", "").Replace(",", "").Replace(" ", "");

return Cellphone.Trim().Replace("(", "").Replace(")", "").Replace("-", "").Replace(" ", "").Replace(".", "").Replace(",", "");

Apenas por garantia, acredito que é bom tentar evitar qualquer possível forma que o usuário possa querer digitar.

2022-11-22 13:24 UTC, LucasPerinWarren commented on API/API.csproj
>    </ItemGroup>
Referencia ao AutoMapper deve estar na AppServices, e o package de DependencyInjection do AutoMapper, depende do AutoMapper original, portanto não há a necessidade de usar ambos.
```suggestion
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
  </ItemGroup>
```

2022-11-22 13:29 UTC, LucasPerinWarren commented on AppServices/AppServices.csproj
> +		<PackageReference Include="FluentValidation.AspNetCore" Version="11.2.2" />
[Comentário similar](https://github.com/LuanFortunatoW/EverestBackendDotnet/pull/3/files#r1029322895)
```suggestion
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
		<PackageReference Include="FluentValidation.AspNetCore" Version="11.2.2" />
```

2022-11-22 13:30 UTC, LucasPerinWarren commented on AppServices/Services/CustomerAppService.cs
>          }
```suggestion
            var _mappedCustomer = _mapper.Map<Customer>(customer);
            return _service.Create(_mappedCustomer);
        }
```

2022-11-22 13:31 UTC, LucasPerinWarren commented on AppServices/Services/CustomerAppService.cs
> +            _mappedCustomer.Id = id;
```suggestion
            var _mappedCustomer = _mapper.Map<Customer>(customer);
            _mappedCustomer.Id = id;
```

2022-11-22 13:33 UTC, LucasPerinWarren commented on DomainModels/Customer.cs
>              City = city;
Por que emailConfirmation foi deletado da entidade ?

2022-11-22 13:35 UTC, LuanFortunatoW commented on DomainModels/Customer.cs
>              City = city;
Achei q já não fosse necessário manter porque a verificação é feita na camada de AppService

2022-11-22 13:36 UTC, LucasPerinWarren commented on Infrastructure.CrossCuting/Extensions/ValidatorExtensions.cs
> +    {
Um método validador não deve estar dentro da camada de crosscutting, visto que você não utiliza ele em diversas camadas. Pelo fato de utilizá-lo apenas dentro dos validadores, convém mantê-lo dentro da AppServices, junto dos validadores das entidades.

2022-11-22 13:36 UTC, LucasPerinWarren requested changes
Verificar comentários.

2022-11-22 13:43 UTC, gregoryzimmerwarren approved these changes
Deixei mais estes comentários, mas acredito que da minha parte seja isso. Já vou deixar aprovado.

2022-11-22 13:43 UTC, gregoryzimmerwarren commented on AppModels/Customers/CustomerResult.cs
> +            Cellphone = cellphone.formatCellphone();
```suggestion
            Cpf = cpf;
            Cellphone = cellphone;
```

2022-11-22 13:43 UTC, gregoryzimmerwarren commented on AppModels/Customers/CustomerResult.cs
> +            Cellphone = cellphone.formatCellphone();
Não tem a necessidade de fazer a formatação porque está vindo do banco, então já está formatado.

2022-11-22 13:43 UTC, gregoryzimmerwarren commented on AppModels/Customers/CustomerResult.cs
> +            PostalCode = postalCode.formatPostalCode();
```suggestion
            PostalCode = postalCode;
```

2022-11-22 13:43 UTC, gregoryzimmerwarren commented on AppModels/Customers/CustomerResult.cs
> +            PostalCode = postalCode.formatPostalCode();
Idem comentário anterior.

2022-11-22 13:44 UTC, LucasPerinWarren commented on DomainModels/Customer.cs
>              City = city;
Justo, só estamos utilizando para fazer a validação, pode ignorar esse comentário, desculpe.

2022-11-22 14:55 UTC, LucasPerinWarren commented on AppServices/Validators/CustomerCreateValidator.cs
>                  .WithMessage("Cpf is not valid.");
Corrigir importação.
```suggestion
                .Must(isValidCpf)
                .WithMessage("Cpf is not valid.");
```

2022-11-22 14:57 UTC, LucasPerinWarren commented on AppServices/Validators/ValidatorExtensions.cs
> +    {
O método não é uma extension, e sim uma validação. Algo como CpfValidator, StringValidator, se encaixa melhor.

2022-11-22 14:58 UTC, LucasPerinWarren commented on AppServices/Validators/ValidatorExtensions.cs
> +        {
Nomes de classe/métodos seguir padrão PascalCase
```suggestion
        public static bool IsValidCpf(string cpf)
        {
```

2022-11-22 14:58 UTC, LucasPerinWarren requested changes
Verificar comentários.

2022-11-22 15:23 UTC, LucasPerinWarren approved these changes

2022-11-22 16:27 UTC, viniciusoliveira-warren commented on AppModels/AppModels.csproj
> +	</ItemGroup>
Camada de dtos não deve ter referencia a nenhum projeto

2022-11-22 16:29 UTC, LuanFortunatoW commented on AppModels/AppModels.csproj
> +	</ItemGroup>
O ideal é deixar a extension no mesmo projeto?

2022-11-22 16:43 UTC, LucasPerinWarren commented on AppModels/AppModels.csproj
> +	</ItemGroup>
Vou me permitir auxiliar a review do Vini neste ponto. Suas extensions da domain já são suficientes, visto que você mapeia as entidades no profile, portanto não há a necessidade de formatar novamente.

2022-11-22 17:26 UTC, viniciusoliveira-warren approved these changes

2022-11-22 17:52 UTC, merged