feat: switching singleton instance to database
LuanFortunatoW/EverestBackendDotnet pull request #5
Opened 2022-11-23 16:24 UTC by LuanFortunatoW

# Card
[EV-996](https://warren.atlassian.net/browse/EV-996)

# Feats

- Aplicar Configurations/Mappings via Assembly

2022-11-23 16:25 UTC, viniciusoliveira-warren commented on API/API.csproj
> +	<ProjectReference Include="..\Infrastructure.Data\Infrastructure.Data.csproj" />
Api não deve conhecer camada de dados

2022-11-23 16:29 UTC, viniciusoliveira-warren commented on DomainServices/Services/CustomerService.cs
> +            //customer.Id = _dBContext.Set<Customer>().LastOrDefault()?.Id + 1 ?? 1;
Sem comentários

2022-11-23 16:32 UTC, viniciusoliveira-warren commented on DomainServices/Services/CustomerService.cs
> +            if (_dBContext.Set<Customer>().Any(_customer => _customer.Email == customer.Email))
Está fazendo 3x _dBContext.Set<Customer>(), podemos salvar em uma variável e reutilizar

2022-11-23 16:33 UTC, viniciusoliveira-warren commented on Infrastructure.Data/EverestDbContext.cs
> +        }
```suggestion
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfigurationsFromAssembly(typeof(EverestDBContext).Assembly);
        }
```

2022-11-23 16:33 UTC, viniciusoliveira-warren commented on Infrastructure.Data/Mappings/CustomerEntityTypeConfiguration.cs
> +            builder.ToTable("Customer");
Tabelas sempre no plural porque é uma lista de Customer
```suggestion
            builder.ToTable("Customers");
```

2022-11-23 16:42 UTC, viniciusoliveira-warren commented on Infrastructure.Data/Migrations/20221123143206_CustomerMigration.cs
> +                    Email = table.Column<string>(type: "longtext", nullable: true)
Esse campo não justifica uso do longtext, ajustar tipo de acordo com a quantidade de caracteres que será salvo por coluna. [Motivo para estudo](https://stackoverflow.com/questions/7314682/what-is-the-disadvantage-to-using-a-mysql-longtext-sized-field-when-every-entry)

2022-11-23 16:42 UTC, viniciusoliveira-warren commented on Infrastructure.Data/Migrations/20221123143206_CustomerMigration.cs
> +                        .Annotation("MySql:CharSet", "utf8mb4"),
Esse campo não justifica uso do longtext, ajustar tipo de acordo com a quantidade de caracteres que será salvo por coluna. [Motivo para estudo](https://stackoverflow.com/questions/7314682/what-is-the-disadvantage-to-using-a-mysql-longtext-sized-field-when-every-entry)

2022-11-23 16:43 UTC, ghost commented on Infrastructure.Data/Migrations/20221123143206_CustomerMigration.cs
> +                        .Annotation("MySql:CharSet", "utf8mb4"),
Esse campo não justifica uso do longtext, ajustar tipo de acordo com a quantidade de caracteres que será salvo por coluna. [Motivo para estudo](https://stackoverflow.com/questions/7314682/what-is-the-disadvantage-to-using-a-mysql-longtext-sized-field-when-every-entry)

2022-11-23 16:43 UTC, viniciusoliveira-warren commented on Infrastructure.Data/Migrations/20221123143206_CustomerMigration.cs
> +                        .Annotation("MySql:CharSet", "utf8mb4"),
Esse campo não justifica uso do longtext, ajustar tipo de acordo com a quantidade de caracteres que será salvo por coluna. [Motivo para estudo](https://stackoverflow.com/questions/7314682/what-is-the-disadvantage-to-using-a-mysql-longtext-sized-field-when-every-entry)

2022-11-29 18:39 UTC, gregoryzimmerwarren requested changes
Deixei dois comentários, qualquer dúvida estou a disposição.

2022-11-29 18:39 UTC, gregoryzimmerwarren commented on DomainServices/Services/CustomerService.cs
> +            if (_dbSet.Any(_customer => _customer.Email == customer.Email))
Nos teus ArgumentException eu colocaria o email e o cpf que o usuário informou no erro, só para ficar ainda mais claro.

2022-11-29 18:39 UTC, gregoryzimmerwarren commented on DomainServices/Services/CustomerService.cs
> +            var _customer = GetById(customer.Id);
Precisa fazer a verificação da existência do email ou cpf repetidos para outro Id antes de fazer o update.

2022-11-29 19:35 UTC, LuanFortunatoW commented on DomainServices/Services/CustomerService.cs
> +            var _customer = GetById(customer.Id);
Tá no próximo card

2022-11-30 12:11 UTC, gregoryzimmerwarren approved these changes

2023-01-11 16:23 UTC, merged